exec spInsertSpecilizedIn 'Audit','1','tahmed1'
exec spInsertSpecilizedIn 'ORACLE','1','tahmed1'
exec spInsertSpecilizedIn 'JAVA','1','tahmed1'
exec spInsertSpecilizedIn 'Cryltal Report','1','tahmed1'
exec spInsertSpecilizedIn 'Accounts','1','tahmed1'
exec spInsertSpecilizedIn 'Credit','1','tahmed1'
exec spInsertSpecilizedIn 'Marketing','1','tahmed1'
exec spInsertSpecilizedIn 'Recovery','1','tahmed1'
exec spInsertSpecilizedIn 'Technology','1','tahmed1'
exec spInsertSpecilizedIn 'MIS','1','tahmed1'
exec spInsertSpecilizedIn 'Operations','1','tahmed1'
exec spInsertSpecilizedIn 'Risk Management','1','tahmed1'
exec spInsertSpecilizedIn 'Branch Management','1','tahmed1'
exec spInsertSpecilizedIn 'Sales Team Management','1','tahmed1'
exec spInsertSpecilizedIn 'Department Head','1','tahmed1'
exec spInsertSpecilizedIn 'Human Resources','1','tahmed1'
exec spInsertSpecilizedIn 'Front Desk','1','tahmed1'
exec spInsertSpecilizedIn 'Administration','1','tahmed1'
exec spInsertSpecilizedIn 'Data Entry','1','tahmed1'
exec spInsertSpecilizedIn 'Call Center','1','tahmed1'
exec spInsertSpecilizedIn 'Service','1','tahmed1'
exec spInsertSpecilizedIn 'Factoring','1','tahmed1'
exec spInsertSpecilizedIn 'Deposit','1','tahmed1'
exec spInsertSpecilizedIn 'Home Loan Finance','1','tahmed1'
exec spInsertSpecilizedIn 'Lease Finance','1','tahmed1'
exec spInsertSpecilizedIn 'General Management','1','tahmed1'
exec spInsertSpecilizedIn 'Credit Analyst','1','tahmed1'
exec spInsertSpecilizedIn 'Credit Risk Management','1','tahmed1'
exec spInsertSpecilizedIn 'Portfolio Management','1','tahmed1'
exec spInsertSpecilizedIn 'Not Matched ','1','tahmed1'




exec spInsertOccupation 'ACCOUNTANT','1','tahmed1'
exec spInsertOccupation 'ARTIST','1','tahmed1'
exec spInsertOccupation 'BACHELOR','1','tahmed1'
exec spInsertOccupation 'BANKER','1','tahmed1'
exec spInsertOccupation 'BARBER','1','tahmed1'
exec spInsertOccupation 'BARRISTER AT LAW','1','tahmed1'
exec spInsertOccupation 'BLACKSMITH','1','tahmed1'
exec spInsertOccupation '','1','tahmed1'
exec spInsertOccupation 'HOUSEWIFE','1','tahmed1'
exec spInsertOccupation 'BOATMAN','1','tahmed1'
exec spInsertOccupation 'BUSINESS','1','tahmed1'
exec spInsertOccupation 'CONTRACTOR','1','tahmed1'
exec spInsertOccupation 'COOK','1','tahmed1'
exec spInsertOccupation 'DOCTOR','1','tahmed1'
exec spInsertOccupation 'DRIVER','1','tahmed1'
exec spInsertOccupation 'ENGINEER','1','tahmed1'
exec spInsertOccupation 'FARMER','1','tahmed1'
exec spInsertOccupation 'FISHERMAN','1','tahmed1'
exec spInsertOccupation 'GOVERNMENT SERVICE','1','tahmed1'
exec spInsertOccupation 'GUARD','1','tahmed1'
exec spInsertOccupation 'JOURNALIST','1','tahmed1'
exec spInsertOccupation 'JUDGE','1','tahmed1'
exec spInsertOccupation 'JUSTICE','1','tahmed1'
exec spInsertOccupation 'LABOR','1','tahmed1'
exec spInsertOccupation 'LAWYER','1','tahmed1'
exec spInsertOccupation 'MECHANIC','1','tahmed1'
exec spInsertOccupation 'MEMBER OF PERLIAMENT','1','tahmed1'
exec spInsertOccupation 'MERCHANT MARINE OFFICER','1','tahmed1'
exec spInsertOccupation 'MINISTER','1','tahmed1'
exec spInsertOccupation 'NURSE','1','tahmed1'
exec spInsertOccupation 'OTHERS','1','tahmed1'
exec spInsertOccupation 'POLITICIAN','1','tahmed1'
exec spInsertOccupation 'PORTER','1','tahmed1'
exec spInsertOccupation 'POTTER','1','tahmed1'
exec spInsertOccupation 'PRESIDENT','1','tahmed1'
exec spInsertOccupation 'PRIME MINISTER','1','tahmed1'
exec spInsertOccupation 'PRIVATE SERVICE','1','tahmed1'
exec spInsertOccupation 'RETIRED(GOVERNMENT SERVICE)','1','tahmed1'
exec spInsertOccupation 'RETIRED(PRIVATE SERVICE)','1','tahmed1'
exec spInsertOccupation 'RETIRED TECHNOCRAT','1','tahmed1'
exec spInsertOccupation 'SPEAKER','1','tahmed1'
exec spInsertOccupation 'STUDENT','1','tahmed1'
exec spInsertOccupation 'SWEEPER','1','tahmed1'
exec spInsertOccupation 'TAILOR','1','tahmed1'
exec spInsertOccupation 'TEACHER','1','tahmed1'
exec spInsertOccupation 'UNEMPLOYED','1','tahmed1'
exec spInsertOccupation 'WASHERMAN','1','tahmed1'



exec spInsertDocumentType 'CV','0','1','tahmed1'
exec spInsertDocumentType 'Cover Letter','0','1','tahmed1'
exec spInsertDocumentType 'Other','0','1','tahmed1'